---
title: "Introduction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## About this workshop

The previous workshops in this bootcamp were focused on introducing some basic functionality of the languages to people who had 0 previous exposure. This workshop builds upon those skills by working through some real tasks and problems that you may encounter in your work.

The two main topics of this workshop are:

* File manipulation on the command line 
* Visualization and analysis of decreasing marginal utility curves

Along the way, we will review and expand upon the knowledge you gained from the previous three workshops. 

To do this workshop, you will need the following packages to do this workshop:

* rmarkdown
* ggplot2
* tidyverse

Finally, clone this repository by entering the following into your command line:

```{bash, eval = FALSE}
git clone https://github.com/pommevilla/p3.bootcamp.da1.2019.git
```

I encourage you to do the following:

* Work together with a partner
* Look up function documentation
* Search online for help
* Ask questions

[p3-landing]: https://www.predictivephenomicsinplants.iastate.edu/
[intro-to-r]: https://github.com/pommevilla/p3.bootcamp.r.2019
[intro-to-python]: https://github.com/pommevilla/p3.bootcamp.python.2019
[paul-github]: https://github.com/pommevilla
[intro-to-unix]: https://github.com/skDooley/shell_tutorial
[shane-github]: https://github.com/skDooley
[data-1]: https://github.com/pommevilla/p3.bootcamp.da1.2019
